apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: postgres:10.5
    generation: null
    importPolicy: {}
    name: "10.5"
status:
  dockerImageRepository: ""
