apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: /projects/kompose convert --provider=openshift
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  selector:
    io.kompose.service: database
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
      - image: ' '
        name: super-database
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/init.sql
          name: database-claim0
      restartPolicy: Always
      volumes:
      - name: database-claim0
        persistentVolumeClaim:
          claimName: database-claim0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - super-database
      from:
        kind: ImageStreamTag
        name: database:10.5
    type: ImageChange
status: {}
