apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: /projects/kompose convert --provider=openshift
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    io.kompose.service: kafka
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafka
    spec:
      containers:
      - args:
        - sh
        - -c
        - bin/kafka-server-start.sh config/server.properties --override listeners=${KAFKA_LISTENERS}
          --override advertised.listeners=${KAFKA_ADVERTISED_LISTENERS} --override
          zookeeper.connect=${KAFKA_ZOOKEEPER_CONNECT}
        env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://localhost:9092
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: LOG_DIR
          value: /tmp/logs
        image: ' '
        name: kafka
        ports:
        - containerPort: 9092
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - kafka
      from:
        kind: ImageStreamTag
        name: kafka:0.11.3-kafka-2.1.0
    type: ImageChange
status: {}
