apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /projects/kompose convert --provider=openshift
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: monitoring
  name: monitoring
spec:
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    io.kompose.service: monitoring
status:
  loadBalancer: {}
