apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: monitoring
  name: monitoring
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: prom/prometheus
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
